In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

Datastructure in pandas

1. Series(1 Dimension)
2. Dataframe(2 Dimension)

# 1. Series

In [4]:
age = np.random.randint(23,50,100)

In [5]:
lst = [34,23,890,34,90]

temp = pd.Series(lst)

print(type(temp))

<class 'pandas.Series'>

In [6]:
age

array([39, 42, 31, 31, 38, 28, 40, 34, 36, 27, 40, 41, 27, 31, 33, 29, 37,
       33, 27, 27, 32, 25, 46, 41, 30, 23, 27, 36, 41, 47, 45, 27, 36, 46,
       39, 44, 25, 36, 33, 32, 39, 24, 43, 42, 29, 23, 29, 48, 24, 37, 40,
       23, 42, 41, 26, 26, 46, 38, 40, 27, 33, 46, 49, 49, 36, 25, 36, 36,
       42, 24, 25, 38, 40, 37, 24, 42, 46, 37, 27, 32, 30, 48, 25, 26, 46,
       26, 42, 37, 49, 40, 38, 36, 33, 24, 32, 42, 49, 29, 48, 34])

In [7]:
age_s = pd.Series(age)

In [8]:
age_s

0     39
1     42
2     31
3     31
4     38
      ..
95    42
96    49
97    29
98    48
99    34
Length: 100, dtype: int64

In [9]:
print(age_s[10])

40

In [10]:
[f"emp_age-{i}" for i in range(101,201)]

['emp_age-101',
 'emp_age-102',
 'emp_age-103',
 'emp_age-104',
 'emp_age-105',
 'emp_age-106',
 'emp_age-107',
 'emp_age-108',
 'emp_age-109',
 'emp_age-110',
 'emp_age-111',
 'emp_age-112',
 'emp_age-113',
 'emp_age-114',
 'emp_age-115',
 'emp_age-116',
 'emp_age-117',
 'emp_age-118',
 'emp_age-119',
 'emp_age-120',
 'emp_age-121',
 'emp_age-122',
 'emp_age-123',
 'emp_age-124',
 'emp_age-125',
 'emp_age-126',
 'emp_age-127',
 'emp_age-128',
 'emp_age-129',
 'emp_age-130',
 'emp_age-131',
 'emp_age-132',
 'emp_age-133',
 'emp_age-134',
 'emp_age-135',
 'emp_age-136',
 'emp_age-137',
 'emp_age-138',
 'emp_age-139',
 'emp_age-140',
 'emp_age-141',
 'emp_age-142',
 'emp_age-143',
 'emp_age-144',
 'emp_age-145',
 'emp_age-146',
 'emp_age-147',
 'emp_age-148',
 'emp_age-149',
 'emp_age-150',
 'emp_age-151',
 'emp_age-152',
 'emp_age-153',
 'emp_age-154',
 'emp_age-155',
 'emp_age-156',
 'emp_age-157',
 'emp_age-158',
 'emp_age-159',
 'emp_age-160',
 'emp_age-161',
 'emp_age-162',
 'emp_age-163',
 'emp_age-164',
 'emp_age-165',
 'emp_age-166',
 'emp_age-167',
 'emp_age-168',
 'emp_age-169',
 'emp_age-170',
 'emp_age-171',
 'emp_age-172',
 'emp_age-173',
 'emp_age-174',
 'emp_age-175',
 'emp_age-176',
 'emp_age-177',
 'emp_age-178',
 'emp_age-179',
 'emp_age-180',
 'emp_age-181',
 'emp_age-182',
 'emp_age-183',
 'emp_age-184',
 'emp_age-185',
 'emp_age-186',
 'emp_age-187',
 'emp_age-188',
 'emp_age-189',
 'emp_age-190',
 'emp_age-191',
 'emp_age-192',
 'emp_age-193',
 'emp_age-194',
 'emp_age-195',
 'emp_age-196',
 'emp_age-197',
 'emp_age-198',
 'emp_age-199',
 'emp_age-200']

In [11]:
age_sr = pd.Series(age,index=[f"emp_age-{i}" for i in range(101,201)])

In [12]:
age_sr

emp_age-101    39
emp_age-102    42
emp_age-103    31
emp_age-104    31
emp_age-105    38
               ..
emp_age-196    42
emp_age-197    49
emp_age-198    29
emp_age-199    48
emp_age-200    34
Length: 100, dtype: int64

In [13]:
age_sr['emp_age-110']

np.int64(27)

In [14]:
age_sr.dtypes

dtype('int64')

In [15]:
age_ = pd.Series(age,index=[i for i in range(1,101)],dtype='float16')

In [16]:
age_.dtype

dtype('float16')

In [17]:
age_.mean()

np.float16(35.28)

In [18]:
age_.std()

np.float16(7.7)

In [19]:
age_.describe()

count    100.000000
mean      35.281250
std        7.699219
min       23.000000
25%       27.750000
50%       36.000000
75%       41.000000
max       49.000000
dtype: float64

In [20]:
age_.min()

np.float16(23.0)

In [21]:
age_.max()

np.float16(49.0)

# 2. Dataframe

In [22]:
students = {
    "Name":["Rahul","Krish","Nishu","Priya"],
    "Marks":[34,45,89,46],
    "City":["Delhi","Jaipur","Noida","Mumbai"]
}

In [23]:
type(students)

dict

In [24]:
df = pd.DataFrame(students)

In [25]:
df

    Name  Marks    City
0  Rahul     34   Delhi
1  Krish     45  Jaipur
2  Nishu     89   Noida
3  Priya     46  Mumbai

In [26]:
print(type(df))

<class 'pandas.DataFrame'>

In [27]:
emp = [("Neha",34,45000),("Rohit",33,56000),("Nish",35,65000)]

In [28]:
emp_df = pd.DataFrame(emp)

In [29]:
emp_df

       0   1      2
0   Neha  34  45000
1  Rohit  33  56000
2   Nish  35  65000

In [30]:
employees = pd.DataFrame(emp,columns=["Name","Age","Salary"])

In [31]:
employees

    Name  Age  Salary
0   Neha   34   45000
1  Rohit   33   56000
2   Nish   35   65000

In [32]:
employees = pd.DataFrame(emp,columns=["Name","Age","Salary"],index=[f"emp-{i}" for i in range(1,len(emp)+1) ])

In [33]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [34]:
employees = pd.DataFrame(emp,
                        columns=["Name","Age","Salary"],
                        index=[f"emp-{i}" for i in range(1,len(emp)+1) ],
                        dtype='str'
                        )

In [35]:
employees.dtypes

Name      str
Age       str
Salary    str
dtype: object

In [36]:
employees

        Name Age Salary
emp-1   Neha  34  45000
emp-2  Rohit  33  56000
emp-3   Nish  35  65000

In [37]:
employees.index

Index(['emp-1', 'emp-2', 'emp-3'], dtype='str')

In [38]:
type(employees)

pandas.DataFrame

In [39]:
type(employees['Name'])

pandas.Series

In [40]:
employees['Salary']

emp-1    45000
emp-2    56000
emp-3    65000
Name: Salary, dtype: str

In [41]:
employees

        Name Age Salary
emp-1   Neha  34  45000
emp-2  Rohit  33  56000
emp-3   Nish  35  65000

In [42]:
employees.min()

Name       Neha
Age          33
Salary    45000
dtype: str

In [43]:
employees.describe()

        Name Age Salary
count      3   3      3
unique     3   3      3
top     Neha  34  45000
freq       1   1      1

In [44]:
employees.dtypes

Name      str
Age       str
Salary    str
dtype: object

In [45]:
employees.ndim

2

In [46]:
employees.shape

(3, 3)

In [47]:
employees.index

Index(['emp-1', 'emp-2', 'emp-3'], dtype='str')

In [48]:
employees.values

array([['Neha', '34', '45000'],
       ['Rohit', '33', '56000'],
       ['Nish', '35', '65000']], dtype=object)

In [49]:
employees.size

9

In [50]:
employees

        Name Age Salary
emp-1   Neha  34  45000
emp-2  Rohit  33  56000
emp-3   Nish  35  65000

In [51]:
emps = employees.copy()

In [52]:
emps.loc['Age'] = "Nishu"

In [53]:
emps

        Name    Age Salary
emp-1   Neha     34  45000
emp-2  Rohit     33  56000
emp-3   Nish     35  65000
Age    Nishu  Nishu  Nishu

In [54]:
employees

        Name Age Salary
emp-1   Neha  34  45000
emp-2  Rohit  33  56000
emp-3   Nish  35  65000

In [55]:
employees.info()

<class 'pandas.DataFrame'>
Index: 3 entries, emp-1 to emp-3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      str
 2   Salary  3 non-null      str
dtypes: str(3)
memory usage: 204.0+ bytes

In [56]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [59]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [63]:
orders = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Orders")
order_items = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Order_Items")
customers = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Customers")

In [68]:
customers.head(10)

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
0,C0001,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
1,C0002,Aadhya Sethi,Male,58,New Delhi,Delhi,North,Small Business,2025-06-19
2,C0003,Yash Chatterjee,Female,49,Panipat,Haryana,North,Corporate,2024-08-21
3,C0004,Nisha Patel,Female,64,Kolkata,West Bengal,East,Consumer,2025-07-10
4,C0005,Simran Iyer,Male,23,Jodhpur,Rajasthan,North,Consumer,2022-07-29
5,C0006,Kavya Mehta,Male,43,New Delhi,Delhi,North,Consumer,2023-07-04
6,C0007,Kabir Nair,Male,56,Coimbatore,Tamil Nadu,South,Small Business,2025-11-24
7,C0008,Gurpreet Kaur,Female,64,Noida,Uttar Pradesh,North,Corporate,2025-06-26
8,C0009,Priya Patel,Female,24,Panipat,Haryana,North,Corporate,2023-03-09
9,C0010,Kavya Nair,Female,62,Ludhiana,Punjab,North,Consumer,2022-07-18

In [67]:
customers.tail(10)

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
990,C0991,Aadhya Kapoor,Male,49,Kolkata,West Bengal,East,Consumer,2024-04-27
991,C0992,Arjun Kaur,Male,65,Kochi,Kerala,South,Corporate,2023-11-23
992,C0993,Aadhya Mehta,Male,52,Jalandhar,Punjab,North,Consumer,2025-05-17
993,C0994,Ananya Singh,Female,41,Ahmedabad,Gujarat,West,Small Business,2025-02-01
994,C0995,Manav Bansal,Male,44,Thiruvananthapuram,Kerala,South,Corporate,2022-10-19
995,C0996,Aadhya Malhotra,Female,58,Nagpur,Maharashtra,West,Consumer,2023-07-07
996,C0997,Sneha Joshi,Female,27,Kolkata,West Bengal,East,Small Business,2024-01-06
997,C0998,Kavya Chatterjee,Female,39,Vadodara,Gujarat,West,Corporate,2023-07-27
998,C0999,Ishita Reddy,Male,46,Thiruvananthapuram,Kerala,South,Small Business,2025-01-02
999,C1000,Sanya Khanna,Male,63,Pune,Maharashtra,West,Consumer,2022-10-27

In [77]:
customers.iloc[np.random.randint(0,1000,15)]

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
184,C0185,Ananya Arora,Male,33,Thiruvananthapuram,Kerala,South,Corporate,2023-09-20
323,C0324,Aarav Chatterjee,Male,44,Jaipur,Rajasthan,North,Consumer,2024-06-28
174,C0175,Rahul Sharma,Male,59,Hyderabad,Telangana,South,Consumer,2025-03-07
661,C0662,Rahul Chatterjee,Male,32,Amritsar,Punjab,North,Small Business,2022-03-08
675,C0676,Isha Joshi,Female,38,Varanasi,Uttar Pradesh,North,Consumer,2022-12-27
679,C0680,Sanya Bansal,Male,25,Ludhiana,Punjab,North,Consumer,2022-10-04
175,C0176,Harpreet Chatterjee,Male,22,Mysuru,Karnataka,South,Small Business,2022-08-09
635,C0636,Manav Sharma,Male,53,Madurai,Tamil Nadu,South,Corporate,2025-01-31
636,C0637,Ananya Kaur,Male,56,Jalandhar,Punjab,North,Consumer,2025-12-21
503,C0504,Riya Verma,Female,48,Amritsar,Punjab,North,Consumer,2022-06-28
881,C0882,Aadhya Reddy,Female,40,Kolkata,West Bengal,East,Corporate,2023-08-23
113,C0114,Tanya Joshi,Female,31,Kolkata,West Bengal,East,Consumer,2022-11-15
862,C0863,Rahul Malhotra,Male,21,Noida,Uttar Pradesh,North,Corporate,2023-08-20
243,C0244,Simran Gupta,Male,49,Thiruvananthapuram,Kerala,South,Consumer,2025-05-03
578,C0579,Harpreet Gupta,Male,22,Delhi,Delhi,North,Small Business,2024-01-31