In [ ]:
pip install pandas

In [6]:
import pandas as pd
import numpy as np

Datastructure in pandas

1. Series(1 Dimension)
2. Dataframe(2 Dimension)

# 1. Series

In [7]:
age = np.random.randint(23,50,100)

In [22]:
lst = [34,23,890,34,90]

temp = pd.Series(lst)

print(type(temp))

<class 'pandas.Series'>

In [18]:
age

array([45, 38, 46, 32, 47, 31, 42, 27, 41, 31, 47, 27, 26, 46, 33, 26, 47,
       41, 33, 23, 41, 40, 45, 25, 37, 36, 41, 44, 23, 47, 42, 38, 42, 30,
       27, 44, 47, 34, 39, 25, 24, 45, 26, 34, 48, 31, 45, 38, 25, 23, 28,
       38, 29, 48, 45, 33, 38, 32, 31, 28, 33, 31, 30, 25, 41, 24, 34, 39,
       29, 46, 28, 30, 49, 49, 37, 32, 24, 42, 25, 28, 39, 48, 33, 34, 45,
       46, 32, 39, 34, 45, 29, 26, 40, 33, 23, 33, 30, 29, 23, 44])

In [8]:
age_s = pd.Series(age)

In [24]:
age_s

0     45
1     38
2     46
3     32
4     47
      ..
95    33
96    30
97    29
98    23
99    44
Length: 100, dtype: int64

In [23]:
print(age_s[10])

47

In [25]:
[f"emp_age-{i}" for i in range(101,201)]

['emp_age-101',
 'emp_age-102',
 'emp_age-103',
 'emp_age-104',
 'emp_age-105',
 'emp_age-106',
 'emp_age-107',
 'emp_age-108',
 'emp_age-109',
 'emp_age-110',
 'emp_age-111',
 'emp_age-112',
 'emp_age-113',
 'emp_age-114',
 'emp_age-115',
 'emp_age-116',
 'emp_age-117',
 'emp_age-118',
 'emp_age-119',
 'emp_age-120',
 'emp_age-121',
 'emp_age-122',
 'emp_age-123',
 'emp_age-124',
 'emp_age-125',
 'emp_age-126',
 'emp_age-127',
 'emp_age-128',
 'emp_age-129',
 'emp_age-130',
 'emp_age-131',
 'emp_age-132',
 'emp_age-133',
 'emp_age-134',
 'emp_age-135',
 'emp_age-136',
 'emp_age-137',
 'emp_age-138',
 'emp_age-139',
 'emp_age-140',
 'emp_age-141',
 'emp_age-142',
 'emp_age-143',
 'emp_age-144',
 'emp_age-145',
 'emp_age-146',
 'emp_age-147',
 'emp_age-148',
 'emp_age-149',
 'emp_age-150',
 'emp_age-151',
 'emp_age-152',
 'emp_age-153',
 'emp_age-154',
 'emp_age-155',
 'emp_age-156',
 'emp_age-157',
 'emp_age-158',
 'emp_age-159',
 'emp_age-160',
 'emp_age-161',
 'emp_age-162',
 'emp_age-163',
 'emp_age-164',
 'emp_age-165',
 'emp_age-166',
 'emp_age-167',
 'emp_age-168',
 'emp_age-169',
 'emp_age-170',
 'emp_age-171',
 'emp_age-172',
 'emp_age-173',
 'emp_age-174',
 'emp_age-175',
 'emp_age-176',
 'emp_age-177',
 'emp_age-178',
 'emp_age-179',
 'emp_age-180',
 'emp_age-181',
 'emp_age-182',
 'emp_age-183',
 'emp_age-184',
 'emp_age-185',
 'emp_age-186',
 'emp_age-187',
 'emp_age-188',
 'emp_age-189',
 'emp_age-190',
 'emp_age-191',
 'emp_age-192',
 'emp_age-193',
 'emp_age-194',
 'emp_age-195',
 'emp_age-196',
 'emp_age-197',
 'emp_age-198',
 'emp_age-199',
 'emp_age-200']

In [26]:
age_sr = pd.Series(age,index=[f"emp_age-{i}" for i in range(101,201)])

In [27]:
age_sr

emp_age-101    45
emp_age-102    38
emp_age-103    46
emp_age-104    32
emp_age-105    47
               ..
emp_age-196    33
emp_age-197    30
emp_age-198    29
emp_age-199    23
emp_age-200    44
Length: 100, dtype: int64

In [28]:
age_sr['emp_age-110']

np.int64(31)

In [30]:
age_sr.dtypes

dtype('int64')

In [31]:
age_ = pd.Series(age,index=[i for i in range(1,101)],dtype='float16')

In [33]:
age_.dtype

dtype('float16')

In [34]:
age_.mean()

np.float16(35.47)

In [35]:
age_.std()

np.float16(7.95)

In [36]:
age_.describe()

count    100.000000
mean      35.468750
std        7.949219
min       23.000000
25%       29.000000
50%       34.000000
75%       42.000000
max       49.000000
dtype: float64

In [37]:
age_.min()

np.float16(23.0)

In [38]:
age_.max()

np.float16(49.0)

# 2. Dataframe

In [42]:
students = {
    "Name":["Rahul","Krish","Nishu","Priya"],
    "Marks":[34,45,89,46],
    "City":["Delhi","Jaipur","Noida","Mumbai"]
}

In [44]:
type(students)

dict

In [45]:
df = pd.DataFrame(students)

In [49]:
df

    Name  Marks    City
0  Rahul     34   Delhi
1  Krish     45  Jaipur
2  Nishu     89   Noida
3  Priya     46  Mumbai

In [48]:
print(type(df))

<class 'pandas.DataFrame'>

In [50]:
emp = [("Neha",34,45000),("Rohit",33,56000),("Nish",35,65000)]

In [51]:
emp_df = pd.DataFrame(emp)

In [52]:
emp_df

       0   1      2
0   Neha  34  45000
1  Rohit  33  56000
2   Nish  35  65000

In [53]:
employees = pd.DataFrame(emp,columns=["Name","Age","Salary"])

In [54]:
employees

    Name  Age  Salary
0   Neha   34   45000
1  Rohit   33   56000
2   Nish   35   65000

In [69]:
employees = pd.DataFrame(emp,columns=["Name","Age","Salary"],index=[f"emp-{i}" for i in range(1,len(emp)+1) ])

In [59]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [67]:
employees = pd.DataFrame(emp,
                        columns=["Name","Age","Salary"],
                        index=[f"emp-{i}" for i in range(1,len(emp)+1) ],
                        dtype='str'
                        )

In [68]:
employees.dtypes

Name      str
Age       str
Salary    str
dtype: object

In [70]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [72]:
employees.index

Index(['emp-1', 'emp-2', 'emp-3'], dtype='str')

In [79]:
type(employees)

pandas.DataFrame

In [78]:
type(employees['Name'])

pandas.Series

In [ ]:
employees['Salary']

np.int64(45000)

In [83]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [84]:
employees.min()

Name       Neha
Age          33
Salary    45000
dtype: object

In [85]:
employees.describe()

        Age        Salary
count   3.0      3.000000
mean   34.0  55333.333333
std     1.0  10016.652801
min    33.0  45000.000000
25%    33.5  50500.000000
50%    34.0  56000.000000
75%    34.5  60500.000000
max    35.0  65000.000000

In [86]:
employees.dtypes

Name        str
Age       int64
Salary    int64
dtype: object

In [87]:
employees.ndim

2

In [88]:
employees.shape

(3, 3)

In [89]:
employees.index

Index(['emp-1', 'emp-2', 'emp-3'], dtype='str')

In [90]:
employees.values

array([['Neha', 34, 45000],
       ['Rohit', 33, 56000],
       ['Nish', 35, 65000]], dtype=object)

In [91]:
employees.size

9

In [92]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [93]:
emps = employees.copy()

In [97]:
emps.loc['Age'] = "Nishu"

In [98]:
emps

        Name    Age Salary
emp-1   Neha     34  45000
emp-2  Rohit     33  56000
emp-3   Nish     35  65000
Age    Nishu  Nishu  Nishu

In [99]:
employees

        Name  Age  Salary
emp-1   Neha   34   45000
emp-2  Rohit   33   56000
emp-3   Nish   35   65000

In [101]:
employees.info()

<class 'pandas.DataFrame'>
Index: 3 entries, emp-1 to emp-3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0+ bytes

In [ ]:
pd.DataFrame()