In [1]:
import pandas as pd

In [2]:
orders = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Orders")
order_items = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Order_Items")
customers = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Customers")
products = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Products")
categories = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Categories")
stores = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Stores")
salepersons = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Salespersons")
returns = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Returns")
targets = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Targets")

In [21]:
all_sheet = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name=None)

In [22]:
all_sheet.keys()

dict_keys(['Orders', 'Order_Items', 'Customers', 'Products', 'Categories', 'Stores', 'Salespersons', 'Returns', 'Targets'])

In [25]:
for key,value in all_sheet.items():
    print(key,": ",value.shape)

Orders :  (5000, 10)
Order_Items :  (7394, 8)
Customers :  (1000, 9)
Products :  (95, 8)
Categories :  (19, 3)
Stores :  (96, 7)
Salespersons :  (100, 6)
Returns :  (496, 7)
Targets :  (1920, 5)

In [26]:
for key,value in all_sheet.items():
    print(key,": ",list(value.columns))

Orders :  ['Order_ID', 'Order_Date', 'Customer_ID', 'Store_ID', 'Salesperson_ID', 'Payment_Mode', 'Order_Status', 'Shipping_Date', 'Delivery_Date', 'Sales_Channel']
Order_Items :  ['Order_ID', 'Product_ID', 'Quantity', 'Unit_Price', 'Discount', 'Sales', 'Cost', 'Profit']
Customers :  ['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'State', 'Region', 'Customer_Segment', 'Signup_Date']
Products :  ['Product_ID', 'Product_Name', 'Category_ID', 'Category', 'Subcategory', 'Brand', 'Unit_Cost', 'List_Price']
Categories :  ['Category_ID', 'Category', 'Subcategory']
Stores :  ['Store_ID', 'Store_Name', 'City', 'State', 'Region', 'Store_Type', 'Store_Area_SqFt']
Salespersons :  ['Salesperson_ID', 'Salesperson_Name', 'Base_City', 'State', 'Region', 'Sales_Channel']
Returns :  ['Return_ID', 'Order_ID', 'Product_ID', 'Return_Date', 'Returned_Quantity', 'Return_Reason', 'Refund_Amount']
Targets :  ['Month', 'Store_ID', 'Sales_Target', 'Profit_Target', 'Quantity_Target']

In [29]:
for key,value in all_sheet.items():
    print(key)
    print(value.head())
    print("\n")

Orders
  Order_ID Order_Date Customer_ID Store_ID Salesperson_ID Payment_Mode  \
0  O000001 2025-10-03       C0298     S022          SP061  Credit Card
1  O000002 2025-12-01       C0710     S060          SP077  Credit Card
2  O000003 2025-12-07       C0333     S034          SP068          UPI
3  O000004 2025-05-31       C0737     S019          SP057          UPI
4  O000005 2025-05-21       C0851     S070          SP076   Debit Card

  Order_Status Shipping_Date Delivery_Date Sales_Channel
0    Delivered    2025-10-04    2025-10-09        Online
1    Delivered    2025-12-04    2025-12-09      In-Store
2    Delivered    2025-12-08    2025-12-10      In-Store
3    Delivered    2025-06-03    2025-06-07        Online
4    Delivered    2025-05-23    2025-05-25        Online


Order_Items
  Order_ID Product_ID  Quantity  Unit_Price  Discount   Sales  Cost  Profit
0  O000001      P0064         1         900      0.05   855.0   525   330.0
1  O000002      P0068         1        1550      0.20  1240.0   861   379.0
2  O000003      P0089         3        1400      0.10  3780.0  3270   510.0
3  O000004      P0017         2        3950      0.25  5925.0  5018   907.0
4  O000005      P0090         1       11050      0.10  9945.0  7980  1965.0


Customers
  Customer_ID    Customer_Name  Gender  Age       City        State Region  \
0       C0001      Aarav Gupta  Female   61     Mumbai  Maharashtra   West
1       C0002     Aadhya Sethi    Male   58  New Delhi        Delhi  North
2       C0003  Yash Chatterjee  Female   49    Panipat      Haryana  North
3       C0004      Nisha Patel  Female   64    Kolkata  West Bengal   East
4       C0005      Simran Iyer    Male   23    Jodhpur    Rajasthan  North

  Customer_Segment Signup_Date
0        Corporate  2022-06-02
1   Small Business  2025-06-19
2        Corporate  2024-08-21
3         Consumer  2025-07-10
4         Consumer  2022-07-29


Products
  Product_ID        Product_Name Category_ID     Category  Subcategory  \
0      P0001  Samsung Galaxy A55      CAT001  Electronics  Smartphones
1      P0002   OnePlus Nord CE 4      CAT001  Electronics  Smartphones
2      P0003     Apple iPhone 15      CAT001  Electronics  Smartphones
3      P0004            Vivo V30      CAT001  Electronics  Smartphones
4      P0005    Nothing Phone 2a      CAT001  Electronics  Smartphones

     Brand  Unit_Cost  List_Price
0  Samsung      19789       30400
1  OnePlus      31755       44700
2    Apple       1084        1400
3     Vivo      20974       28700
4  Nothing       1046        1600


Categories
  Category_ID         Category  Subcategory
0      CAT001      Electronics  Smartphones
1      CAT002      Electronics      Laptops
2      CAT003      Electronics        Audio
3      CAT004      Electronics  Accessories
4      CAT005  Home Appliances      Kitchen


Stores
  Store_ID               Store_Name      City   State Region Store_Type  \
0     S001  Ludhiana Flagship Store  Ludhiana  Punjab  North   Flagship
1     S002  Ludhiana Standard Store  Ludhiana  Punjab  North   Standard
2     S003   Ludhiana Express Store  Ludhiana  Punjab  North    Express
3     S004  Amritsar Flagship Store  Amritsar  Punjab  North   Flagship
4     S005  Amritsar Standard Store  Amritsar  Punjab  North   Standard

   Store_Area_SqFt
0             4741
1             1888
2             1403
3             4308
4             1528


Salespersons
  Salesperson_ID Salesperson_Name Base_City        State Region  \
0          SP001      Shweta Shah   Panipat      Haryana  North
1          SP002     Shweta Reddy    Nagpur  Maharashtra   West
2          SP003     Anjali Joshi     Surat      Gujarat   West
3          SP004    Simran Khanna  Siliguri  West Bengal   East
4          SP005     Shweta Mehta    Nashik  Maharashtra   West

     Sales_Channel
0  Territory Sales
1     Key Accounts
2     Key Accounts
3     Inside Sales
4     Key Accounts


Returns
  Return_ID Order_ID Product_ID Return_Date  Returned_Quantity  \
0    R00001  O000015      P0059  2025-12-22                  3
1    R00002  O000016      P0014  2025-07-14                  3
2    R00003  O000018      P0066  2026-04-02                  1
3    R00004  O000027      P0014  2025-11-08                  1
4    R00005  O000029      P0038  2025-04-29                  2

    Return_Reason  Refund_Amount
0    Changed Mind        11985.0
1   Late Delivery        22500.0
2   Quality Issue          225.0
3         Damaged         7125.0
4  Size/Fit Issue         2700.0


Targets
       Month Store_ID  Sales_Target  Profit_Target  Quantity_Target
0 2025-01-01     S001        417000          67600             1446
1 2025-01-01     S002        522700          99700              881
2 2025-01-01     S003        263000          30300             2003
3 2025-01-01     S004        766700         110200             1658
4 2025-01-01     S005        745600         147100             2109

In [31]:
for key,value in all_sheet.items():
    print(key)
    print("-"*10)
    print(value.dtypes)
    print("\n")

Orders
----------
Order_ID                     str
Order_Date        datetime64[us]
Customer_ID                  str
Store_ID                     str
Salesperson_ID               str
Payment_Mode                 str
Order_Status                 str
Shipping_Date     datetime64[us]
Delivery_Date     datetime64[us]
Sales_Channel                str
dtype: object


Order_Items
----------
Order_ID          str
Product_ID        str
Quantity        int64
Unit_Price      int64
Discount      float64
Sales         float64
Cost            int64
Profit        float64
dtype: object


Customers
----------
Customer_ID                    str
Customer_Name                  str
Gender                         str
Age                          int64
City                           str
State                          str
Region                         str
Customer_Segment               str
Signup_Date         datetime64[us]
dtype: object


Products
----------
Product_ID        str
Product_Name      str
Category_ID       str
Category          str
Subcategory       str
Brand             str
Unit_Cost       int64
List_Price      int64
dtype: object


Categories
----------
Category_ID    str
Category       str
Subcategory    str
dtype: object


Stores
----------
Store_ID             str
Store_Name           str
City                 str
State                str
Region               str
Store_Type           str
Store_Area_SqFt    int64
dtype: object


Salespersons
----------
Salesperson_ID      str
Salesperson_Name    str
Base_City           str
State               str
Region              str
Sales_Channel       str
dtype: object


Returns
----------
Return_ID                       str
Order_ID                        str
Product_ID                      str
Return_Date          datetime64[us]
Returned_Quantity             int64
Return_Reason                   str
Refund_Amount               float64
dtype: object


Targets
----------
Month              datetime64[us]
Store_ID                      str
Sales_Target                int64
Profit_Target               int64
Quantity_Target             int64
dtype: object

In [35]:
for key,value in all_sheet.items():
    print(key)
    print("-"*10)
    print(value.isnull().sum(),"\n\n",value.isnull().mean()*100)
    print("\n")

Orders
----------
Order_ID          0
Order_Date        0
Customer_ID       0
Store_ID          0
Salesperson_ID    0
Payment_Mode      0
Order_Status      0
Shipping_Date     0
Delivery_Date     0
Sales_Channel     0
dtype: int64

 Order_ID          0.0
Order_Date        0.0
Customer_ID       0.0
Store_ID          0.0
Salesperson_ID    0.0
Payment_Mode      0.0
Order_Status      0.0
Shipping_Date     0.0
Delivery_Date     0.0
Sales_Channel     0.0
dtype: float64


Order_Items
----------
Order_ID      0
Product_ID    0
Quantity      0
Unit_Price    0
Discount      0
Sales         0
Cost          0
Profit        0
dtype: int64

 Order_ID      0.0
Product_ID    0.0
Quantity      0.0
Unit_Price    0.0
Discount      0.0
Sales         0.0
Cost          0.0
Profit        0.0
dtype: float64


Customers
----------
Customer_ID         0
Customer_Name       0
Gender              0
Age                 0
City                0
State               0
Region              0
Customer_Segment    0
Signup_Date         0
dtype: int64

 Customer_ID         0.0
Customer_Name       0.0
Gender              0.0
Age                 0.0
City                0.0
State               0.0
Region              0.0
Customer_Segment    0.0
Signup_Date         0.0
dtype: float64


Products
----------
Product_ID      0
Product_Name    0
Category_ID     0
Category        0
Subcategory     0
Brand           0
Unit_Cost       0
List_Price      0
dtype: int64

 Product_ID      0.0
Product_Name    0.0
Category_ID     0.0
Category        0.0
Subcategory     0.0
Brand           0.0
Unit_Cost       0.0
List_Price      0.0
dtype: float64


Categories
----------
Category_ID    0
Category       0
Subcategory    0
dtype: int64

 Category_ID    0.0
Category       0.0
Subcategory    0.0
dtype: float64


Stores
----------
Store_ID           0
Store_Name         0
City               0
State              0
Region             0
Store_Type         0
Store_Area_SqFt    0
dtype: int64

 Store_ID           0.0
Store_Name         0.0
City               0.0
State              0.0
Region             0.0
Store_Type         0.0
Store_Area_SqFt    0.0
dtype: float64


Salespersons
----------
Salesperson_ID      0
Salesperson_Name    0
Base_City           0
State               0
Region              0
Sales_Channel       0
dtype: int64

 Salesperson_ID      0.0
Salesperson_Name    0.0
Base_City           0.0
State               0.0
Region              0.0
Sales_Channel       0.0
dtype: float64


Returns
----------
Return_ID            0
Order_ID             0
Product_ID           0
Return_Date          0
Returned_Quantity    0
Return_Reason        0
Refund_Amount        0
dtype: int64

 Return_ID            0.0
Order_ID             0.0
Product_ID           0.0
Return_Date          0.0
Returned_Quantity    0.0
Return_Reason        0.0
Refund_Amount        0.0
dtype: float64


Targets
----------
Month              0
Store_ID           0
Sales_Target       0
Profit_Target      0
Quantity_Target    0
dtype: int64

 Month              0.0
Store_ID           0.0
Sales_Target       0.0
Profit_Target      0.0
Quantity_Target    0.0
dtype: float64

In [36]:
for key,value in all_sheet.items():
    print(key)
    print("-"*10)
    print(value.describe())
    print("\n")

Orders
----------
                       Order_Date               Shipping_Date  \
count                        5000                        5000
mean   2025-11-04 06:54:43.200000  2025-11-06 06:37:43.680000
min           2025-01-01 00:00:00         2025-01-02 00:00:00
25%           2025-06-07 00:00:00         2025-06-10 00:00:00
50%           2025-11-06 00:00:00         2025-11-08 00:00:00
75%           2026-04-03 00:00:00         2026-04-05 00:00:00
max           2026-08-31 00:00:00         2026-09-03 00:00:00

                    Delivery_Date
count                        5000
mean   2025-11-09 06:43:29.280000
min           2025-01-04 00:00:00
25%           2025-06-12 00:00:00
50%           2025-11-10 12:00:00
75%           2026-04-08 00:00:00
max           2026-09-08 00:00:00


Order_Items
----------
          Quantity    Unit_Price     Discount          Sales           Cost  \
count  7394.000000   7394.000000  7394.000000    7394.000000    7394.000000
mean      2.012037   5835.582905     0.089701   10771.209427    7976.962402
std       1.069854   9653.695308     0.069605   21317.164286   16304.519173
min       1.000000    200.000000     0.000000     150.000000     135.000000
25%       1.000000    750.000000     0.050000    1050.000000     748.000000
50%       2.000000   1600.000000     0.100000    2900.000000    2100.000000
75%       3.000000   5800.000000     0.150000    9975.000000    7402.000000
max       4.000000  74400.000000     0.250000  282720.000000  224812.000000

             Profit
count   7394.000000
mean    2794.247025
std     5586.864472
min     -806.000000
25%      245.000000
50%      750.000000
75%     2448.000000
max    57908.000000


Customers
----------
               Age                 Signup_Date
count  1000.000000                        1000
mean     42.622000  2024-01-19 11:22:33.600000
min      21.000000         2022-01-02 00:00:00
25%      32.000000         2023-01-21 00:00:00
50%      43.000000         2024-01-14 00:00:00
75%      54.000000         2025-01-24 18:00:00
max      65.000000         2026-02-08 00:00:00
std      13.046276                         NaN


Products
----------
          Unit_Cost    List_Price
count     95.000000     95.000000
mean    5785.673684   8527.368421
std     8680.460634  12300.617889
min      135.000000    200.000000
25%      702.500000   1175.000000
50%     1999.000000   3500.000000
75%     6592.000000  10225.000000
max    56203.000000  74400.000000


Categories
----------
       Category_ID     Category  Subcategory
count           19           19           19
unique          19            6           18
top         CAT001  Electronics  Accessories
freq             1            4            2


Stores
----------
       Store_Area_SqFt
count        96.000000
mean       2768.895833
std        1224.825749
min         957.000000
25%        1606.750000
50%        2632.000000
75%        3857.250000
max        4884.000000


Salespersons
----------
       Salesperson_ID Salesperson_Name Base_City    State Region Sales_Channel
count             100              100       100      100    100           100
unique            100               91        34       12      4             4
top             SP001     Simran Reddy   Panipat  Gujarat  North  Key Accounts
freq                1                2         6       13     37            29


Returns
----------
                      Return_Date  Returned_Quantity  Refund_Amount
count                         496         496.000000     496.000000
mean   2025-10-31 11:45:29.032258           1.526210    8752.691532
min           2025-01-04 00:00:00           1.000000     160.000000
25%           2025-06-06 00:00:00           1.000000     900.000000
50%           2025-11-04 12:00:00           1.000000    2411.250000
75%           2026-03-10 06:00:00           2.000000    7982.500000
max           2026-08-31 00:00:00           4.000000  134100.000000
std                           NaN           0.816075   15820.679888


Targets
----------
                     Month   Sales_Target  Profit_Target  Quantity_Target
count                 1920    1920.000000    1920.000000      1920.000000
mean   2025-10-16 02:24:00  572553.593750   85905.677083      1459.998437
min    2025-01-01 00:00:00  250200.000000   25900.000000       701.000000
25%    2025-05-24 06:00:00  411075.000000   58900.000000      1078.000000
50%    2025-10-16 12:00:00  571150.000000   82050.000000      1463.000000
75%    2026-03-08 18:00:00  732250.000000  109325.000000      1832.000000
max    2026-08-01 00:00:00  899800.000000  179700.000000      2199.000000
std                    NaN  187494.370602   33517.339108       433.406423

## Join

Join combines the dataframe based on their index.

In [3]:
df1 = pd.DataFrame(
    {
        "Name":["Amit","Riya","Rahul"],
        "Department":["IT","HR","Finance"],
    },index=[101,102,103]
)

In [4]:
df2 = pd.DataFrame(
    {
        "Salary":[50000,60000,45000]
    },index = [101,102,104]
)

In [5]:
df1.join(df2)

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN

In [6]:
df1.join(df2,how='left')

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN

In [7]:
df1.join(df2,how='right')

     Name Department  Salary
101  Amit         IT   50000
102  Riya         HR   60000
104   NaN        NaN   45000

In [8]:
df1.join(df2,how='inner')

     Name Department  Salary
101  Amit         IT   50000
102  Riya         HR   60000

In [9]:
df1.join(df2,how='outer')

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN
104    NaN        NaN  45000.0

In [10]:
df3 = pd.DataFrame(
    {   "EmpID":[101,102,103],
        "Name":["Amit","Riya","Rahul"],
        "Department":["IT","HR","Finance"],
    }
)

In [11]:
df2

     Salary
101   50000
102   60000
104   45000

In [12]:
df3

   EmpID   Name Department
0    101   Amit         IT
1    102   Riya         HR
2    103  Rahul    Finance

In [13]:
df3.join(df2,on='EmpID')

   EmpID   Name Department   Salary
0    101   Amit         IT  50000.0
1    102   Riya         HR  60000.0
2    103  Rahul    Finance      NaN

### Difference between join() and merge()

|Feature | join() | merge() |
|--------|-------|--------|
|Default matching key | index | common columns, when available |
|Column based joining | supported with on parameter | directly supported with on |
|Best Suited for | Joining  data frames based on index | Joining tables using key columns|